# POSTGRESQL DOCKER
version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: stock
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: stock_bank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: